[package]
name = "hephaestus-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ort.workspace = true
ndarray.workspace = true
tokenizers.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
mel_spec = "0.4"

[features]
cuda = ["ort/cuda"]
tensorrt = ["ort/tensorrt"]
coreml = ["ort/coreml"]
integration = []

[dev-dependencies]
hf-hub.workspace = true
tokio.workspace = true
mockall.workspace = true
tempfile.workspace = true
