syntax = "proto3";
package hephaestus.v1;

service InferenceService {
  rpc Infer(InferRequest) returns (InferResponse);
}

message InferRequest {
  string text = 1;
}

message InferResponse {
  string model_id = 1;
  uint64 latency_ms = 2;

  oneof result {
    ClassificationResult classification = 10;
    EmbeddingResult embedding = 11;
    TokenClassificationResult token_classification = 12;
    Seq2SeqResult seq2seq = 13;
  }
}

message ClassificationResult {
  string label = 1;
  float score = 2;
}

message EmbeddingResult {
  repeated float values = 1;
}

message TokenClassificationResult {
  repeated Entity entities = 1;
}

message Entity {
  string word = 1;
  string entity = 2;
  float score = 3;
  uint32 start = 4;
  uint32 end = 5;
}

message Seq2SeqResult {
  string generated_text = 1;
}
