[package]
name = "hephaestus-resolve"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config.workspace = true
aws-sdk-s3.workspace = true
opendal.workspace = true
hf-hub.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["fs", "time"] }

[dev-dependencies]
mockall.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "time"] }
