[package]
name = "hephaestus"
version = "0.1.0"
edition = "2024"

[dependencies]
hephaestus-core = { path = "../hephaestus-core" }
hephaestus-api = { path = "../hephaestus-api" }
hephaestus-resolve = { path = "../hephaestus-resolve" }
anyhow.workspace = true
axum.workspace = true
opendal.workspace = true
envy.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
cuda = ["hephaestus-core/cuda"]
tensorrt = ["hephaestus-core/tensorrt"]
coreml = ["hephaestus-core/coreml"]

[dev-dependencies]
tempfile.workspace = true
